spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http:localhost:8081/api/v1/
          predicates:
            - Patch=/patient/**
        - id: r2
          uri: http:localhost:8082/api/v1/
          predicates:
            - Patch=/medicalrecord/**

  application:
    name: gateway-service
server:
  port: 8888

