package org.medilabo.reporting_service.services.services;

import org.medilabo.reporting_service.config.RuleEngine;
import org.medilabo.reporting_service.model.ReportingPatient;
import org.medilabo.reporting_service.services.interfaces.IAlert;
import org.springframework.stereotype.Service;


@Service
public class AlertService implements IAlert {
    private final RuleEngine ruleEngine;

    public AlertService(RuleEngine ruleEngine) {
        this.ruleEngine = ruleEngine;
    }

    /**
     * Processes alerts for a given patient by evaluating rules using the rule engine.
     *
     * <p>This method checks the patient's data against predefined rules and returns
     * the corresponding alert if any rule is triggered. If no rules are triggered,
     * it returns a default message.
     *
     * @param rp the {@link ReportingPatient} containing patient information and triggers
     * @return the alert message generated by the rule engine, or "No alert" if none apply
     */
    @Override
    public String processAlert(ReportingPatient rp) {
        return ruleEngine.evaluate(rp).orElse("No alert");
    }
}
